%define PAGE_SIZE 4096
%define SIZEOF_STRUCT_CONTEXT (8 * 21)
%define SIZEOF_STRUCT_TASK (SIZEOF_STRUCT_CONTEXT + 8)
%define SIZEOF_STRUCT_PERCPU 0x18

%define GDT_USER_DATA 0x10
%define GDT_TSS 0x30

%define NUM_SYSCALLS 1
%define SYSCALL_ERROR 0xFFFFFFFFFFFFFFFF
